apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
spec:
  hosts:
    - nginx.local.cluster
    - nginx.mrmorais.com
  http:
    - route:
      - destination:
          host: nginx.default.svc.cluster.local
          subset: v1
