apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { template "nginx-demo-chart.fullname" . } }
  labels:
    app: { { template "nginx-demo-chart.name" . } }
    version: { { .Chart.AppVersion } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { tempalte "nginx-demo-chart.name" . } }
      version: { { .Chart.AppVersion } }
  template:
    metadata:
      labels:
        app: { { tempalte "nginx-demo-chart.name" . } }
        version: { { .Chart.AppVersion } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.port } }
              protocol: TCP
