apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "nginx-demo-chart.fullname" . }}
spec:
  hosts: {{ toYaml .Values.gateway.hosts | nindent 4 }}
  gateways:
    - {{ include "nginx-demo-chart.fullname" . }}
  http:
    - route:
        - destination:
            host: {{ include "nginx-demo-chart.fullname" . }}
            port:
              number: 80
