apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: { { template "nginx-demo-chart.fullname" . } }
spec:
  hosts: { { - include ".Values.gateway.hosts" . | nindent 4 } }
  gateways:
    - { { template "nginx-demo-chart.fullname" . } }
  http:
    - route:
        - destination:
            host: { { - include ".Values.gateway.hosts" . | nindent 4 } }
            port:
              number: 80
