apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "nginx-demo-chart.fullname" . }}
spec:
  selector:
    istio: {{ .Values.gateway.ingress | quote }}
  servers:
    - hosts: {{ toYaml .Values.gateway.hosts | nindent 6 }}
      port:
        name: http
        number: 8080
        protocol: HTTP
