apiVersion: v1
kind: Service
metadata:
  name: { { include "nginx-demo-chart.fullname" . } }
  labels:
    app: { { template "nginx-demo-chart.name" . } }
    service: { { template "nginx-demo-chart.name" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: { { include "nginx-demo-chart.name" . } }
